version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      - POSTGRES_DB=codeware
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=adm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: imagem-rockstar:0.1
    container_name: aplicacao_spring_teste
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codeware
      - SPRING_DATASOURCE_USERNAME=adm
      - SPRING_DATASOURCE_PASSWORD=adm

volumes:
  postgres_data:
