FROM eclipse-temurin:21
LABEL maintainer="Lucas.torquato13@hotmail.com"
WORKDIR /app
COPY target/first-spring-app-0.0.1-SNAPSHOT.jar /app/rockstar.jar
ENTRYPOINT ["java", "-jar", "/app/rockstar.jar"]

